### ISSUE TITLE
[frontend] Resolve Test Suite NewRun.test.tsx

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/kubeflow-pipelines#53]
### Steps to reproduce

1. Checkout Branch kfp-46-npm-install
2. `nvm use 14`
3. `npm ci`
4. `npm test`

![image](https://user-images.githubusercontent.com/35379392/196703682-94e5a191-ecbb-4b1a-835f-589ae10788ef.png)

**Comment by mathis-marcotte** [comment]
closing this ticket as we are moving away from pipelines
