### ISSUE TITLE
Pipelines I18n new Content for Upstream (2/6)

### ISSUE THREAD

**Issue by wg102** [StatCan/kubeflow-pipelines#9]
Child of https://github.com/StatCan/kubeflow-pipelines/issues/7

While rebasing, some new content was noticed.
- All Recurring Runs 
- Reccurring List
- Metrics TAb
- Run Details
- RunDetails.tsx -> Tab names
- 
Will need to look into each of those and add the translations + check on missing translation through those pages.

**Comment by wg102** [comment]
Our current work into getting pipelines synced with version 1.5.1 may have closed some of these. [See comment on the epic ](https://github.com/StatCan/kubeflow-pipelines/issues/7#issuecomment-1022302789)

**Comment by Souheil-Yazji** [comment]
Stale issue.
